os: linux
dist: xenial

language: php

services:
  - mysql

notifications:
  email: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

env:
  jobs:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=nightly WP_MULTISITE=0
    - WP_VERSION=nightly WP_MULTISITE=1
  global:
    - PATH="$(pwd):$TRAVIS_BUILD_DIR/vendor/bin:$HOME/.composer/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$(pwd)"

before_install:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - mv wp-cli.phar wp
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

before_script:
  - composer validate

script: composer test

jobs:
  fast_finish: true
  include:
    - stage: lint
      before_script:
        - composer global require ergebnis/composer-normalize
      script:
        - composer lint
        - composer normalize --dry-run
    - stage: coverage
      before_install: skip
      script:
        - composer test -- --coverage-clover=coverage.xml
      after_script:
        - bash <(curl -s https://codecov.io/bash)

stages:
  - lint
  - test
  - coverage
